=begin
Copyright (c) 2018 Aspose Pty Ltd. All Rights Reserved.

Licensed under the MIT (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

      https://github.com/aspose-omr-cloud/aspose-omr-cloud-ruby/blob/master/LICENSE

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.


#Aspose.OMR for Cloud API Reference

#Aspose.OMR for Cloud helps performing optical mark recognition in the cloud

OpenAPI spec version: 1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.0-SNAPSHOT

=end

# Common files
require 'aspose_omr_cloud/api_client'
require 'aspose_omr_cloud/api_error'
require 'aspose_omr_cloud/version'
require 'aspose_omr_cloud/configuration'

# Models
require 'aspose_omr_cloud/models/aspose_response'
require 'aspose_omr_cloud/models/file_info'
require 'aspose_omr_cloud/models/omr_function_param'
require 'aspose_omr_cloud/models/omr_response_details'
require 'aspose_omr_cloud/models/omr_response_content'
require 'aspose_omr_cloud/models/omr_response_info'
require 'aspose_omr_cloud/models/payload'
require 'aspose_omr_cloud/models/recognition_statistics'
require 'aspose_omr_cloud/models/server_stat'
require 'aspose_omr_cloud/models/omr_response'

# APIs
require 'aspose_omr_cloud/api/omr_api'

module AsposeOmrCloud
  class << self
    # Customize default settings for the SDK using block.
    #   AsposeOmrCloud.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
